#!/usr/bin/env bash 
# Displays numbers from 1 to 100 in list format.
# Displays FizzBuzz when the number is a multiple of 3 and 5.
# Displays Fizz when the number is multiple of 3.
# Displays Buzz when the number is a multiple of 5.
# Otherwise, displays the number.
# In a list format.

for (( j = 0 ; j <= 100 ; j++ ))
do
	if ((j % 3 == 0 && j % 5 == 0 ))
	then 
		echo "FizzBuzz"
	elif (( j % 3 == 0 ))
	then 
		echo "Fizz"
	elif (( j % 5 == 0 ))
	then 
		echo "Buzz"
	else
		echo " $j "
	fi
done
