#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# the 9th iteration shows Best School, then Hi on a new line

i=1
while (( $i <= 10 ))
do
	
	if [ $i -eq 10 ];
	then
		echo "Hi"
	fi
		echo "Best School"
		((i++))
done
